---
title: "EDA"
output: html_document
---

## EDA

```{r}
library(tidyverse)
library(p8105.datasets)
library(ggridges)
library(patchwork)
```

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
Import the weather data
```{r}
data("weather_df")

weather_df=
  weather_df |> 
  mutate(month=floor_date(date, unit = "month"))
```

Make plots
```{r}
weather_df |> 
  ggplot(aes(x=prcp)) +
  geom_histogram()
```

Check for extreme values.
```{r}
weather_df |> 
  filter(prcp>1000) #filtering data, do we need to include these values?
```

Look at data again.
```{r}
weather_df |> 
  filter(tmax >= 20, tmax <= 30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_point(alpha = .75)
```
## Add groups
```{r}
weather_df |>
  group_by(name, month)
```

Counting things
```{r}
weather_df |>
  group_by(name, month) |>
  summarize(
    n = n() #also a n_distinct function, which can counts up distinct instances instead of total number
    )
```
You can count directly too
```{r}
weather_df |> 
  count(name)
```
## Making better summaries
```{r}
weather_summary <- weather_df |>
  group_by(name, month) |>
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_tmin = median(tmin, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE)
  )
```

Groups are now summarized.
```{r}
weather_summary <- weather_df |>
  group_by(name, month) |>
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) |> 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) |>
  knitr::kable(digits = 2)
```

## Mutate with groups 
```{r}
#mutate comes up a lot with grouping, also with summarize
weather_df |> 
  group_by(name) |> 
  mutate(
    mean_tmax = mean(tmax, na.rm=TRUE), #compute is affected by grouping structure, mean goes along with group
    center_tmax=tmax-mean_tmax
  ) |> 
  ggplot(aes(x=date, y=center_tmax, color = name)) +
  geom_point()
```
Look for cold days
```{r}
weather_df |> 
  group_by(name, month) |> 
  mutate(temp_rank = min_rank(desc(tmin))) |> 
  filter(temp_rank < 2)
```

What about lags?
```{r}
weather_df |> #grouping makes correct
  group_by(name) |> 
  mutate(lagged_tmax=lag(tmax))
```

Using the variables we created
```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    temp_change = tmax - lag(tmax)
  ) |> 
  summarize(
    sd_tmax_change = sd(temp_change, na.rm = TRUE),
    tmax_change_max = max(temp_change, na.rm = TRUE)
            )
```
Which day did that change occur?
```{r}
weather_df |>
  group_by(name) |>
  mutate(
    temp_change = tmax - lag(tmax),
    change_rank = min_rank(desc(temp_change))
  ) |> 
  filter(
    change_rank<2
  )
```













